# http://www.appveyor.com/docs/appveyor-yml

# Test against these versions of Node.js and io.js
environment:
  matrix:
    - nodejs_version: "0.12"
    - nodejs_version: "2"
    - nodejs_version: "0.11"
    - nodejs_version: "0.10"
    - nodejs_version: "0.8"
    - nodejs_version: "1"
    - nodejs_version: "1.5.1"

matrix:
  allow_failures:
    - nodejs_version: "2"

platform:
  - x64
  - x86

# Install scripts. (runs after repo cloning)
install:
  # Make sure to use the right platform environment
  - if %platform% == x64 ( CALL "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" amd64 )
  - if %platform% == x86 ( CALL "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" amd64_x86 )
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform
  # Typical npm stuff.
  - set PATH=%APPVEYOR_BUILD_FOLDER%\node_modules\.bin;%APPDATA%\npm;%PATH%
  # Update npm itself if pre-version 2.x
  - ps: If ( (& npm --version) -lt "2." ) {& npm install -g npm@2.11 }
  # Install with dependencies
  - npm install --msvs_version=2013

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - npm test --msvs_version=2013

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{branch}-{build}"
